### ISSUE TITLE
Correción elementos tras migración (Classpip Express)

### ISSUE THREAD

**Issue by DanielDCa** [TFGiando/classpip-express-dev#2]
Despues de migrar la aplicacion a ultima version de Ionic, algunos elementos no funcionan como se esperaban. Es el caso del componente movil-express que jugando en diferentes tipos de juegos, cuando seleccionas mediante botones, barras, etc., aparece un error de consola que no esta influyendo pero estaria mejor revisarlo.
Se adjunta imagen de los elemento en cuestion:

**Comment by gabrielp6** [comment]
![Image](https://user-images.githubusercontent.com/73360260/197820675-8dc5b2bf-c92c-4fba-b083-1c87ebcf8d34.PNG)

**Comment by gabrielp6** [comment]
![Image](https://user-images.githubusercontent.com/73360260/200131329-75158ace-c922-4839-87ff-81ed7b4d1202.png)
